# SLR

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

In [2]:
d1=pd.read_csv('OneDrive/Documents/Housing.csv')

In [3]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [4]:
x=d1['area']
y=d1['price']

In [5]:
x

0      7420
1      8960
2      9960
3      7500
4      7420
       ... 
540    3000
541    2400
542    3620
543    2910
544    3850
Name: area, Length: 545, dtype: int64

In [6]:
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

In [8]:
x_train=np.array(x_train)
x_train=x_train.reshape(-1,1)

In [54]:
#print(x_train)

In [10]:
x_test=np.array(x_test)
x_test=x_test.reshape(-1,1)

In [11]:
#SLR

lr=LinearRegression()
le=lr.fit(x_train,y_train)
pred=le.predict(x_test)

In [12]:
z=pred.round(3)

In [13]:
z

array([3625561.286, 3880968.017, 5650891.855, 3869765.968, 4351454.101,
       4638226.571, 4969807.239, 4458993.777, 3585233.908, 4503801.975,
       4167740.487, 5795174.254, 4270799.344, 4683034.769, 4145336.388,
       4234952.785, 4306645.902, 4252876.064, 6027280.722, 6260283.353,
       3988507.694, 4660630.67 , 3673506.059, 5406687.174, 4678553.949,
       3894410.477, 4582216.323, 4270799.344, 4010911.793, 4324569.182,
       6287168.272, 5292426.268, 4234952.785, 3831678.999, 4010911.793,
       8357307.039, 4288722.623, 4647188.21 , 4181182.947, 3181960.122,
       4277520.573, 4069162.451, 4884671.662, 4907075.761, 9701552.992,
       6699403.698, 5131116.753, 4257356.884, 5019096.257, 5682705.676,
       4122932.289, 5131116.753, 3697254.404, 4055719.991, 6072088.92 ])

In [14]:
y_test

491     2835000
515     2450000
126     5880000
425     3360000
75      6650000
404     3493000
368     3675000
281     4270000
243     4550000
167     5285000
544     1750000
36      8043000
343     3850000
138     5740000
174     5250000
294     4200000
215     4830000
428     3325000
115     6020000
176     5250000
251     4515000
268     4382000
292     4200000
483     2940000
249     4543000
108     6107500
429     3325000
307     4165000
518     2450000
199     4907000
6      10150000
280     4270000
70      6790000
424     3360000
447     3150000
10      9800000
420     3360000
267     4403000
234     4620000
449     3150000
448     3150000
472     3010000
365     3703000
147     5600000
7      10150000
401     3500000
44      7560000
330     3990000
9       9800000
121     5950000
471     3010000
39      7910000
197     4956000
507     2590000
8       9870000
Name: price, dtype: int64

In [15]:
error=mean_absolute_error(y_test,pred)

In [16]:
error

1213927.7328248962

In [17]:
le.coef_   # m
le.intercept_  #c
print('equation of line is ', le.coef_,'x +' ,le.intercept_)

equation of line is  [448.08198417] x + 2442624.8482522564


In [18]:
le.coef_

array([448.08198417])

In [19]:
le.intercept_

2442624.8482522564

In [20]:
import  sklearn

In [53]:
#help(sklearn)

In [22]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [23]:
df=pd.read_csv('OneDrive\Documents\CustomerChurn.csv')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [25]:
from sklearn.preprocessing import LabelEncoder


In [43]:
le=LabelEncoder()
df['gender']=le.fit_transform(df['gender'])
df['Partner']=le.fit_transform(df['Partner'])
df['Dependents']=le.fit_transform(df['Dependents'])
df['Churn']=le.fit_transform(df['Churn'])
df['InternetService']=le.fit_transform(df['InternetService'])
df['Contract']=le.fit_transform(df['Contract'])
df['PaymentMethod']=le.fit_transform(df['PaymentMethod'])
df['MonthlyCharges']=le.fit_transform(df['MonthlyCharges'])
df['TotalCharges']=le.fit_transform(df['TotalCharges'])

In [44]:
x=df[['gender','Dependents','TotalCharges','MonthlyCharges','Contract','SeniorCitizen','tenure','PaymentMethod','InternetService']]

In [45]:
y=df['Churn']

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [47]:
x_train.dtypes

gender             int64
Dependents         int64
TotalCharges       int64
MonthlyCharges     int64
Contract           int64
SeniorCitizen      int64
tenure             int64
PaymentMethod      int64
InternetService    int64
dtype: object

In [39]:
y_train.dtypes

dtype('int32')

In [35]:
x_test

gender  Dependents TotalCharges  MonthlyCharges  Contract  \
4537       1           0       836.35           49.80         0   
3617       0           0        810.7           48.35         0   
6185       1           0       5231.3          103.95         1   
1892       1           0       207.35           50.95         0   
1589       0           0       493.65           64.95         0   
...      ...         ...          ...             ...       ...   
391        1           0      2309.55           84.80         0   
1322       0           0       187.75           19.95         0   
3659       1           0       7332.4          109.90         1   
2513       1           1      1054.75           19.20         2   
210        1           0         84.5           46.00         0   

      SeniorCitizen  tenure  PaymentMethod  InternetService  
4537              0      17              3                0  
3617              1      18              2                0  
6185              0      50              2                1  
1892              1       4              1                0  
1589              1       7              2                0  
...             ...     ...            ...              ...  
391               1      27              0                0  
1322              0      10              0                2  
3659              0      67              1                1  
2513              0      52              3                2  
210               0       2              1                0  

[1761 rows x 9 columns]

In [48]:
lg=LogisticRegression()
lr=lg.fit(x_train,y_train)
preds=lr.predict(x_test)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [49]:
preds

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

In [50]:
y_test

5758    0
4169    1
3875    1
1067    0
3925    0
       ..
6187    0
5225    0
4741    0
1928    1
4228    1
Name: Churn, Length: 1761, dtype: int64

In [51]:
acc=accuracy_score(y_test,preds)

In [52]:
acc

0.794434980124929